### ISSUE TITLE
TRIC Realignment Fails with Obscure Error Message

### ISSUE THREAD

**Issue by DarioS** [msproteomicstools/msproteomicstools#76]
I have a dataset consisting of 43 cancer samples. TRIC runs fine for a few minutes, then stops with an unclear error message. Running the realignment with just 3 of the samples in the dataset as a small software test case does not produce any error. The R command I used is :

```
system(paste("feature_alignment.py --in", paste(PSMfiles, collapse = ' '),
             "--out biostat/datasets/SWATH/cancer/allAligned.csv",
             "--method LocalMST --realign_method lowess"))
```

The error message is :

```
    ...            ...
Run 0_23 maps to  data/170620_PC5_OV_489_SW_2.mzML
Run 0_24 maps to  data/170620_PC5_OV_490_SW_1.mzML
Run 0_25 maps to  data/170620_PC5_OV_490_SW_2.mzML
Traceback (most recent call last):
  File "biostat/software/Python/bin/feature_alignment.py", line 773, in <module>
    main(options)
  File "biostat/software/Python/bin/feature_alignment.py", line 717, in main
    runs = reader.parse_files(options.realign_method != "diRT", options.verbosity)
  File "biostat/software/Python/local/lib/python2.7/site-packages/msproteomicstoolslib/format/SWATHScoringReader.py", line 193, in parse_files
    self.parse_row(current_run, this_row, read_exp_RT)
  File "biostat/software/Python/local/lib/python2.7/site-packages/msproteomicstoolslib/format/SWATHScoringReader.py", line 268, in parse_row
    fdr_score = float(this_row[run.header_dict[fdr_score_name]])
ValueError: could not convert string to float: 
```

Changing `PSMfiles` to `PSMfiles[1:3]` avoids the error.

I notice that in the file output by PyProphet for OV_490_SW_2, one of the `d_score` is missing.

![image](https://user-images.githubusercontent.com/631218/31590923-d5652ca2-b264-11e7-852e-b111b3b06dd4.png)

This missingness happens to one row in 2 of the 43 samples. Is it intended that PyProphet sometimes outputs rows with differing numbers of elements (55 in this row and the other defective one, but 56 for all others) and TRIC should handle such a situation or is it rather a bug in PyProphet which TRIC is not expected to handle?

**Comment by grosenberger** [comment]
PyProphet should always provide a finite d_score value for all peak groups, so there is definitely something going wrong. Which version of PyProphet and which options are you using? Could you please provide a minimum example where that produces this error, so I can have a look at it?

**Comment by DarioS** [comment]
I provide [a compressed TSV file](https://au-mynotebook.labarchives.com/share/Data%2520Files/MjIuMXwyNzYzOS8xNy0xMS9UcmVlTm9kZS8zMTQ3MjM4NjEyfDU2LjA5OTk5OTk5OTk5OTk5NA==) output by OpenSwathWorkflow and the command to create a faulty PyProphet CSV is the same as the one in the recently published protocol. `pyprophet --ignore.invalid_score_columns --d_score.cutoff=0.5 test.tsv`. The resulting `test_with_dscore.csv` file (which is actually a tab-separated file - don't know why it has .csv extension) contains one row that lacks one of the standard columns.

```
> table(lineLengths)
lineLengths
    55     56 
     1 240202 
```

The line number of the faulty row in the text file is

```
> which(lineLengths == 55)
[1] 88903
```

**Comment by grosenberger** [comment]
It seems that the column ``var_library_sangle`` for the query ``DECOY_52917_VTNTMRK_2_run0`` is set to ``NA``, which excludes the entry from scoring.

I have not observed this problem before, but if the files are not processed in any way after OpenSwathWorkflow (by R, Excel, etc), this would indicate a problem in OpenSwathWorkflow. To follow up, I would require the TraML and mzML with the parameters used to generate the file. You could also have a quick look at the TraML and check whether ``DECOY_52917_VTNTMRK_2_run0`` has any special values for the library intensity.

Another option is to rename ``var_library_sangle`` to ``library_sangle``, which excludes the score for PyProphet.

**Comment by bretttully** [comment]
I have observed this problem coming out of OpenSwathWorkflow on a number of occasions now (about 10% of a recent set of 100's of SWATH samples). I haven't had time to look into the cause, but the following patch to `SWATHScoringReader.py` (~line 268) will work around the issue:

```{python}
to_float = lambda x: float('nan' if x == '' else x)
try:
    fdr_score = to_float(this_row[run.header_dict[fdr_score_name]])
    #fdr_score = 0.0001
    protein_name = this_row[run.header_dict[protein_id_col]]
    thisid = this_row[run.header_dict[unique_feature_id_name]]
    diff_from_assay_seconds = to_float(this_row[run.header_dict[diff_from_assay_in_sec_name]])
    d_score = to_float(this_row[run.header_dict[dscore_name]])
    #d_score = 2
except KeyError:
    if self.errorHandling == "strict": 
        raise Exception("Did not find essential column.")

# Optional attributes
intensity = -1
if intensity_name in run.header_dict:
    intensity = to_float(this_row[run.header_dict[intensity_name]])
if "decoy" in run.header_dict:
    decoy = this_row[run.header_dict[decoy_name]]
```

**Comment by hroest** [comment]
@bretttully can you create a PR for this?

**Comment by bretttully** [comment]
I reckon this is because of an error coming from OpenSwath::Scoring::SpectralAngle. The naive implementation you have there will fail if the input vectors are the same, or the same with opposite direction. c.f. https://stackoverflow.com/questions/2827393/angles-between-two-n-dimensional-vectors-in-python/13849249#13849249

```
import numpy as np

def unit_vector(vector):
    """ Returns the unit vector of the vector.  """
    return vector / np.linalg.norm(vector)

def angle_between(v1, v2):
    """ Returns the angle in radians between vectors 'v1' and 'v2'::

            >>> angle_between((1, 0, 0), (0, 1, 0))
            1.5707963267948966
            >>> angle_between((1, 0, 0), (1, 0, 0))
            0.0
            >>> angle_between((1, 0, 0), (-1, 0, 0))
            3.141592653589793
    """
    v1_u = unit_vector(v1)
    v2_u = unit_vector(v2)
    return np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))
```

**Comment by DarioS** [comment]
Thanks to Brett for finding a likely cause of the errors we've been experiencing. @hroest or @grosenberger might like to relocate this issue to the OpenMS GitHub repository so that the source of the problem can be tracked.
