### ISSUE TITLE
TRIC errors

### ISSUE THREAD

**Issue by eseble** [msproteomicstools/msproteomicstools#79]
Hello,
After running PyProphet I am tryingto run TRIC on my "with_dscore_filtered.csv" files. I am using the parameters: feature_alignment.py --file_format openswath --method LocalMST --max_rt_diff 40 --target_fdr 0.01 --max_fdr_quality 0.05 --mst:useRTCorrection True --mst:Stdev_multiplier 3.0 --alignment_score 0.0001 --realign_method lowess --matrix_output_method full --dscore_cutoff 1.0 --frac_selected 0 --disable_isotopic_grouping.

First I got an error saying:
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\nonparametric\smoothers_lowess.py:165: RuntimeWarning: invalid value encountered in true_divideres = _lowess(y, x, frac=frac, it=it, delta=delta)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\feature_alignment.py", line 773, in <module> main(options)
  File "C:\ProgramData\Anaconda3\Scripts\feature_alignment.py", line 748, in main options.mst_local_stdev, options.mst_use_ref, options.force)
  File "C:\ProgramData\Anaconda3\Scripts\feature_alignment.py", line 510, in doMSTAlignment max_rt_diff, force=force)
  File "C:\ProgramData\Anaconda3\lib\sitepackages\msproteomicstoolslib\algorithms\alignment\AlignmentHelper.py", line 195, in addDataToTrafo sm_0_1.initialize(data_0, data_1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\msproteomicstoolslib\math\Smoothing.py", line 387, in initialize self.internal_interpolation.initialize(result[0], result[1])
  File "C:\ProgramData\Anaconda3\lib\site-packages\msproteomicstoolslib\math\Smoothing.py", line 639, in initialize self.f = interp1d(data1s, data2s)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 504, in __init__"least %d entries" % minval)
ValueError: x and y arrays must have at least 2 entries

I found the files that produced the error and deleted them and now I got a different error: 
Warning, zero data!
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\feature_alignment.py", line 773, in <module> main(options)
  File "C:\ProgramData\Anaconda3\Scripts\feature_alignment.py", line 748, in main options.mst_local_stdev, options.mst_use_ref, options.force)
  File "C:\ProgramData\Anaconda3\Scripts\feature_alignment.py", line 510, in do STAlignment
    max_rt_diff, force=force)
  File "C:\ProgramData\Anaconda3\lib\site-packages\msproteomicstoolslib\algoritms\alignment\AlignmentHelper.py", line 183, in addDataToTrafo
    raise Exception("No data available for alignment %s vs %s" % (id_0, id_1) )
Exception: No data available for alignment 0_0 vs 0_2

Does this mean that there are no peakgroups within my RT window below the FDR treshold in one of the runs being compared and so the confidence transfer cannot be made? Or am I completely off base?

As I understand the mapping only occurs between chromatographically similar runs, however my samples are triplicates run in different days and this error always appears when the tree compares a run from day 1 with one of day 2. Can this mean that they are too chromatographically different to be aligned?

Thanks

**Comment by hroest** [comment]
Well, while the algorithm only compares chromatographically similar runs, it first needs to find these runs. For this it performs a all-against-all initial linear regression which is where the problem occurs. This is indeed possible if there are no shared peptides below the value specified in `--alignment_score` , the first idea would be to increase that value and see what happens

**Comment by eseble** [comment]
That makes sense. As the error appeared after the Computed Tree list I thought the similar runs were already selected.

I have increased the --alignment_score but I still had to delete 9 runs of 114 for TRIC to work.
Which --alignment_score value would you say is the maximum that would still give good alignment?

Thanks a lot

**Comment by hroest** [comment]
in general the default value for alignment_score works well, that is why we have chosen it as default. Is it possible that in your dataset you do not have many results with good scores (low q-value) or that the samples are very different?
